version: 19
jobs:
- name: PR check
  steps:
  - !UseTemplateStep
    name: Execute Tests
    templateName: Execute Tests
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Trial Docker Container Build
    templateName: Trial Docker Container Build
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Update Master
  steps:
  - !UseTemplateStep
    name: Execute Tests
    templateName: Execute Tests
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Publish Docker Container
    templateName: Publish Docker Conatiner
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
stepTemplates:
- name: Checkout Code
  steps:
  - !CheckoutStep
    name: Checkout Code
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetBuildVersionStep
    name: Set Build Version From Setup.py
    buildVersion: '@script:Python Get Version From Setup.py@'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetBuildDescriptionStep
    name: Set Build Description
    buildDescription: "version: @build_version@\r\nbranch: @branch@\r\ncommit: @commit_hash@"
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Execute Tests
  steps:
  - !UseTemplateStep
    name: Checkout Code
    templateName: Checkout Code
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run Pytest
    runInContainer: true
    image: python:3.11
    interpreter: !DefaultInterpreter
      commands:
      - pip install -e .
      - pytest
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Trial Docker Container Build
  steps:
  - !UseTemplateStep
    name: Checkout Code
    templateName: Checkout Code
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: Build Docker Container
    tags: '@build_version@ @commit_hash@'
    publish: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Publish Docker Conatiner
  steps:
  - !UseTemplateStep
    name: Checkout Code
    templateName: Checkout Code
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Execute Tests
    templateName: Execute Tests
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: Publish Docker Container
    tags: '@build_version@'
    publish: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
