version: 19
stepTemplates:
- name: Checkout Code
  steps:
  - !CheckoutStep
    name: Checkout Code
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Write Build Version to file:BUILD_VERSION
    runInContainer: true
    image: python:3.11
    interpreter: !DefaultInterpreter
      commands:
      - python setup.py --version > BUILD_VERSION
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetBuildVersionStep
    name: Set Build Version
    buildVersion: '@file:BUILD_VERSION@'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Set Build Version
  steps:
  - !CommandStep
    name: Write Build Version to file:BUILD_VERSION
    runInContainer: true
    image: python 3.11
    interpreter: !DefaultInterpreter
      commands:
      - python setup.py --version > BUILD_VERSION
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetBuildVersionStep
    name: Set Build Version
    buildVersion: '@file:BUILD_VERSION@'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Execute Tests
  steps:
  - !UseTemplateStep
    name: Checkout Code
    templateName: Checkout Code
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run Pytest
    runInContainer: true
    image: python:3.11
    interpreter: !DefaultInterpreter
      commands:
      - pip install -e .
      - pip install -U pytest
      - pytest
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Trial Docker Container Build
  steps:
  - !UseTemplateStep
    name: Checkout Code
    templateName: Checkout Code
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: Build Docker Container
    tags: '@build_version@'
    publish: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Push Docker Container to Dockerhub
  steps:
  - !UseTemplateStep
    name: Checkout Code
    templateName: Checkout Code
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Publish to Docker Hub
    runInContainer: true
    image: docker
    interpreter: !DefaultInterpreter
      commands:
      - build_version=@build_version@
      - echo $build_version
      - docker build -t mullinmax/@project_name@:latest -t mullinmax/@project_name@:$build_version
      - echo @secrets:mullinmax_docker_hub_password@ | docker login -u mullinmax --password-stdin
      - docker push mullinmax/@project_name@:latest
      - docker push mullinmax/@project_name@:$build_version
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
jobs:
- name: PR Tests
  jobExecutor: docker-executor
  steps:
  - !UseTemplateStep
    name: Execute Tests
    templateName: Execute Tests
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Trial Docker Container Build
    templateName: Trial Docker Container Build
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Update Master
  jobExecutor: docker-executor
  steps:
  - !UseTemplateStep
    name: Execute Tests
    templateName: Execute Tests
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Push Docker Container to Docker Hub
    templateName: Push Docker Container to Dockerhub
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: groovy script test
  steps:
  - !UseTemplateStep
    name: Checkout Code
    templateName: Checkout Code
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: groovy script test
    runInContainer: true
    image: python:3.11
    interpreter: !DefaultInterpreter
      commands:
      - echo @script:groovy script test@
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
