version: 19
stepTemplates:
- name: Checkout Code
  steps:
  - !CheckoutStep
    name: Checkout Code
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetBuildVersionStep
    name: Set Build Version From Setup.py
    buildVersion: '@script:Python Get Version From Setup.py@'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Execute Tests
  steps:
  - !UseTemplateStep
    name: Checkout Code
    templateName: Checkout Code
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run Pytest
    runInContainer: true
    image: python:3.11
    interpreter: !DefaultInterpreter
      commands:
      - pip install -e .
      - pip install -U pytest
      - pytest
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Trial Docker Container Build
  steps:
  - !UseTemplateStep
    name: Checkout Code
    templateName: Checkout Code
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: Build Docker Container
    tags: '@build_version@ @commit_hash@'
    publish: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Push Docker Container to Dockerhub
  steps:
  - !UseTemplateStep
    name: Checkout Code
    templateName: Checkout Code
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Execute Tests
    templateName: Execute Tests
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Publish to Docker Hub
    runInContainer: true
    image: docker
    interpreter: !DefaultInterpreter
      commands:
      - build_version=@script:Python Get Version From Setup.py@
      - echo $build_version
      - docker build -t mullinmax/@project_name@:latest -t mullinmax/@project_name@:$build_version
      - echo @secrets:mullinmax_docker_hub_password@ | docker login -u mullinmax --password-stdin
      - docker push mullinmax/@project_name@:latest
      - docker push mullinmax/@project_name@:$build_version
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
jobs:
- name: PR Tests
  jobExecutor: docker-executor
  steps:
  - !UseTemplateStep
    name: Execute Tests
    templateName: Execute Tests
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Trial Docker Container Build
    templateName: Trial Docker Container Build
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: version_string
    allowEmpty: false
    multiline: false
    defaultValueProvider: !ScriptingDefaultValue
      scriptName: Python Get Version From Setup.py
  triggers:
  - !PullRequestUpdateTrigger
    params:
    - name: version_string
      valuesProvider: !ScriptingValues
        scriptName: Python Get Version From Setup.py
      secret: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Update Master
  jobExecutor: docker-executor
  steps:
  - !UseTemplateStep
    name: Execute Tests
    templateName: Execute Tests
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Push Docker Container to Docker Hub
    templateName: Push Docker Container to Dockerhub
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: version_string
    allowEmpty: false
    multiline: false
    defaultValueProvider: !ScriptingDefaultValue
      scriptName: Python Get Version From Setup.py
  triggers:
  - !BranchUpdateTrigger
    branches: master
    params:
    - name: version_string
      valuesProvider: !ScriptingValues
        scriptName: Python Get Version From Setup.py
      secret: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
